name: 'flutter_tracker'
description: 'A Family Tracker for Flutter'
version: '1.0.0+44'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: 'flutter'

  cupertino_icons: '^1.0.6'
  firebase_auth: '^4.15.3'
  firebase_messaging: '^14.7.9'
  firebase_remote_config: '^4.3.8'
  cloud_firestore: '^4.13.6'
  google_sign_in: '^6.2.1'
  flutter_map: '^6.1.0'
  redux: '^5.0.0'
  flutter_redux: '^0.10.0'
  redux_epics: '^0.15.1'
  rxdart: '^0.27.7'
  flutter_background_geolocation: '^4.13.4'
  flutter_native_timezone: '^2.0.0'
  wakelock_plus: '^1.1.4'
  share_plus: '^7.2.1'
  sliding_up_panel: '^2.0.0+1'
  intl: '^0.19.0'
  another_flushbar: '^1.12.30'
  rflutter_alert: '^2.0.7'
  simple_animations: '^5.0.2'
  timeago_flutter: '^3.6.0'
  package_info_plus: '^5.0.1'
  device_info_plus: '^9.1.1'
  camera: '^0.10.5+9'
  image_picker: '^1.0.7'
  connectivity_plus: '^5.0.2'
  battery_plus: '^4.1.0'
  path_provider: '^2.1.2'
  crypto: '^3.0.3'
  latlong2: '^0.9.0'
  in_app_purchase: '^3.1.11'
  google_mobile_ads: '^4.0.0'
  webview_flutter: '^4.4.4'
  syncfusion_flutter_datepicker: '^24.1.41'
  flutter_animate: '^4.5.0'
  retry: '^3.1.2'
  permission_handler: '^11.1.0'
  flutter_slidable: '^3.0.1'
  cached_network_image: '^3.3.1'
  flutter_compass: '^0.8.0'
  sticky_headers: '^0.3.0'
  logger: '^2.0.2+1'
  network_info_plus: '^4.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - 'assets/flutter_tracker-icon.png'
    - 'assets/flutter_tracker-logo.png'
    - 'assets/flutter_tracker-logo-shadow.png'